#!/usr/bin/env python3
"""Generate and run a first BOUT++ reduced-physics validation case.

This is intentionally a first-rung validation harness, not a proof of a reactor
claim. It maps the current fusion design surrogate into a 1D BOUT++ conduction
case so the workflow has a reproducible BOUT++ executable check and a structured
output summary.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import netCDF4
import numpy as np

from fusion_engine_v5.engine.config import DEFAULT_DESIGN
from fusion_engine_v5.engine.plasma_model import evaluate_case
from fusion_engine_v5.engine.reactor_simulation import simulate_reactor


REPO = Path(__file__).resolve().parent
DEFAULT_BOUT_TOP = Path("/root/Documents/Codex/2026-05-26/can-you-make-a-list-of/BOUT-dev")
DEFAULT_BOUT_BUILD = DEFAULT_BOUT_TOP / "build"


def _safe_float(value: Any, default: float = 0.0) -> float:
    try:
        return float(value)
    except Exception:
        return default


def _evaluate_design() -> tuple[dict[str, Any], dict[str, Any], dict[str, Any]]:
    design = dict(DEFAULT_DESIGN)
    plasma = evaluate_case(
        design["R"],
        design["a"],
        design["kappa"],
        design["B0"],
        design["Ip"],
        design["Ti"],
        design["Te"],
        design["H98"],
        design["fG"],
        design["frac_cap"],
    )
    reactor = simulate_reactor(design, blanket_validate=False)
    return design, plasma, reactor


def _mapped_bout_parameters(design: dict[str, Any], plasma: dict[str, Any], reactor: dict[str, Any]) -> dict[str, float]:
    wall_load = _safe_float(reactor.get("wall_load", reactor.get("raw_wall_load", plasma.get("wn_mw_m2", 1.0))), 1.0)
    raw_wall_load = _safe_float(reactor.get("raw_wall_load", plasma.get("wn_mw_m2", wall_load)), wall_load)
    control = _safe_float(reactor.get("tct_control_strength"), 0.0)
    lithium_mod = _safe_float(reactor.get("lithium_wall_modifier"), 1.0)

    # Keep the BOUT++ demo in a numerically gentle range while preserving trends:
    # hotter wall loading increases the perturbation, and stronger modeled
    # transport/control increases effective diffusivity.
    t_scale = max(0.05, min(5.0, wall_load / 2.0))
    chi = max(0.05, min(8.0, 0.75 + 2.25 * control + 0.25 * max(lithium_mod - 1.0, 0.0)))
    width = max(0.08, min(0.6, 0.2 / max(lithium_mod, 0.25)))

    return {
        "chi": float(chi),
        "t_scale": float(t_scale),
        "gaussian_width": float(width),
        "wall_load_mw_m2": float(wall_load),
        "raw_wall_load_mw_m2": float(raw_wall_load),
        "tct_control_strength": float(control),
        "lithium_wall_modifier": float(lithium_mod),
        "ne_m3": _safe_float(plasma.get("ne_m3"), 0.0),
        "B0_T": _safe_float(plasma.get("B0_T", design.get("B0")), 0.0),
        "Te_keV": _safe_float(plasma.get("Te_keV", design.get("Te")), 0.0),
        "Ti_keV": _safe_float(design.get("Ti"), 0.0),
        "betaN": _safe_float(plasma.get("betaN"), 0.0),
        "qstar": _safe_float(plasma.get("qstar"), 0.0),
    }


def _write_bout_inp(
    case_dir: Path,
    params: dict[str, float],
    nout: int,
    *,
    ny: int = 100,
    dy: float = 0.2,
    boundary: str = "dirichlet_o4(0.0)",
    output_step: float = 0.1,
) -> None:
    case_dir.mkdir(parents=True, exist_ok=True)
    text = f"""#
# Generated by bout_validation_bridge.py
# Purpose: reduced BOUT++ conduction sanity check for the current fusion design.
#

MXG = 0

[mesh]
nx = 1
ny = {int(ny)}
nz = 1
dy = {float(dy):.8g}
symmetricGlobalY = true
ixseps1 = -1
ixseps2 = -1

[conduction]
chi = {params["chi"]:.8g}

[T]
scale = {params["t_scale"]:.8g}
function = gauss(y-pi, {params["gaussian_width"]:.8g})
bndry_all = {boundary}

[solver]
output_step = {float(output_step):.8g}
nout = {int(nout)}
"""
    (case_dir / "BOUT.inp").write_text(text, encoding="utf-8")


def _run_bout(case_dir: Path, bout_build: Path) -> None:
    exe = bout_build / "examples" / "conduction" / "conduction"
    if not exe.exists():
        raise FileNotFoundError(f"BOUT++ conduction executable not found: {exe}")

    env = os.environ.copy()
    env["UCX_TLS"] = os.environ.get("BOUT_UCX_TLS", "self")
    result = subprocess.run(
        [str(exe), "-d", str(case_dir)],
        check=False,
        env=env,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )
    (case_dir / "bout_stdout.log").write_text(result.stdout, encoding="utf-8")
    (case_dir / "bout_stderr.log").write_text(result.stderr, encoding="utf-8")
    if result.returncode != 0:
        sys.stderr.write(result.stdout[-4000:])
        sys.stderr.write(result.stderr[-4000:])
        raise subprocess.CalledProcessError(result.returncode, [str(exe), "-d", str(case_dir)])


def _summarize_output(case_dir: Path) -> dict[str, float]:
    output = case_dir / "BOUT.dmp.0.nc"
    if not output.exists():
        raise FileNotFoundError(f"BOUT++ output not found: {output}")

    with netCDF4.Dataset(output) as ds:
        temp = np.asarray(ds.variables["T"][:], dtype=float)
        time = np.asarray(ds.variables["t_array"][:], dtype=float)

    peak = np.max(np.abs(temp), axis=(1, 2, 3))
    initial_peak = float(peak[0])
    final_peak = float(peak[-1])
    decay_ratio = float(final_peak / initial_peak) if initial_peak else float("nan")

    return {
        "time_start": float(time[0]),
        "time_end": float(time[-1]),
        "initial_peak_abs_T": initial_peak,
        "final_peak_abs_T": final_peak,
        "peak_decay_ratio": decay_ratio,
        "mean_peak_abs_T": float(np.mean(peak)),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--bout-top", type=Path, default=Path(os.environ.get("BOUT_TOP", DEFAULT_BOUT_TOP)))
    parser.add_argument("--bout-build", type=Path, default=Path(os.environ.get("BOUT_BUILD", DEFAULT_BOUT_BUILD)))
    parser.add_argument("--case-dir", type=Path, default=None)
    parser.add_argument("--nout", type=int, default=20)
    parser.add_argument("--keep-existing", action="store_true")
    args = parser.parse_args()

    design, plasma, reactor = _evaluate_design()
    params = _mapped_bout_parameters(design, plasma, reactor)

    if args.case_dir is None:
        stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
        case_dir = REPO / "validation_runs" / f"bout_conduction_{stamp}"
    else:
        case_dir = args.case_dir

    if case_dir.exists() and not args.keep_existing:
        shutil.rmtree(case_dir)

    _write_bout_inp(case_dir, params, args.nout)
    _run_bout(case_dir, args.bout_build)
    bout_summary = _summarize_output(case_dir)

    summary = {
        "case_dir": str(case_dir),
        "bout_top": str(args.bout_top),
        "bout_build": str(args.bout_build),
        "mapped_parameters": params,
        "plasma_summary": {
            "pfus_mw": _safe_float(plasma.get("pfus_mw"), 0.0),
            "pbrem_mw": _safe_float(plasma.get("pbrem_mw"), 0.0),
            "ptr_mw": _safe_float(plasma.get("ptr_mw"), 0.0),
            "wn_mw_m2": _safe_float(plasma.get("wn_mw_m2"), 0.0),
            "betaN": _safe_float(plasma.get("betaN"), 0.0),
            "qstar": _safe_float(plasma.get("qstar"), 0.0),
            "bootstrap_frac": _safe_float(plasma.get("bootstrap_frac"), 0.0),
        },
        "reactor_summary": {
            "score": _safe_float(reactor.get("score"), 0.0),
            "net_electric": _safe_float(reactor.get("net_electric"), 0.0),
            "wall_load": _safe_float(reactor.get("wall_load"), 0.0),
            "raw_wall_load": _safe_float(reactor.get("raw_wall_load"), 0.0),
            "tct_control_strength": _safe_float(reactor.get("tct_control_strength"), 0.0),
            "tct_risk_R": _safe_float(reactor.get("tct_risk_R"), 0.0),
            "tct_risk_H": _safe_float(reactor.get("tct_risk_H"), 0.0),
            "event_loss_frac": _safe_float(reactor.get("event_loss_frac"), 0.0),
        },
        "bout_summary": bout_summary,
        "interpretation": (
            "PASS: BOUT++ ran the mapped reduced conduction case and the peak "
            "temperature perturbation decayed."
            if bout_summary["peak_decay_ratio"] < 1.0
            else "CHECK: BOUT++ ran, but peak perturbation did not decay."
        ),
    }

    summary_path = case_dir / "summary.json"
    summary_path.write_text(json.dumps(summary, indent=2, sort_keys=True), encoding="utf-8")
    print(json.dumps(summary, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
