#!/usr/bin/env python3
"""Run BOUT++ operator identities on proportional DIII-D machine meshes."""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import tempfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import netCDF4
import numpy as np

from diiid_bout_elm_mesh_smoke import write_serial_topology_grid


REPO = Path(__file__).resolve().parent
DEFAULT_EXE = REPO / "validation_models" / "diiid_operator_probe" / "build" / "diiid_operator_probe"
DEFAULT_RUN_DIR = REPO / "validation_runs" / "diiid_bout_operator_validation_default"
MESH_GENERATOR = REPO / "diiid_mesh_convergence_consistency.py"
MESH_NAMES = ("coarse", "base", "fine")


def write_input(case_dir: Path, grid: Path) -> None:
    text = f"""# Generated by diiid_bout_operator_validation.py
MZ = 8
zperiod = 1
MXG = 2
MYG = 2

[mesh]
file = "{grid.resolve()}"

[mesh:paralleltransform]
type = shifted

[solver]
type = rk4
nout = 0

[state]
function = 0
scale = 0
bndry_all = neumann
"""
    (case_dir / "BOUT.inp").write_text(text, encoding="utf-8")


def run_case(executable: Path, case_dir: Path) -> None:
    environment = dict(os.environ)
    environment["UCX_TLS"] = environment.get("BOUT_UCX_TLS", "self")
    result = subprocess.run(
        [str(executable), "-d", str(case_dir)],
        env=environment,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode:
        (case_dir / "bout_stdout.log").write_text(result.stdout, encoding="utf-8")
        (case_dir / "bout_stderr.log").write_text(result.stderr, encoding="utf-8")
        raise RuntimeError(f"BOUT++ operator probe failed for {case_dir.name}")


def metrics(case_dir: Path) -> dict[str, Any]:
    with netCDF4.Dataset(case_dir / "BOUT.dmp.0.nc") as dataset:
        fields = {
            name: np.asarray(dataset[name][:], dtype=float)[2:-2, 2:-2, :]
            for name in (
                "ddx_psi",
                "ddy_psi",
                "gradpar_psi",
                "delp2_one",
                "bracket_self",
            )
        }
    results = {}
    expected = {
        "ddx_psi": np.ones_like(fields["ddx_psi"]),
        "ddy_psi": np.zeros_like(fields["ddy_psi"]),
        "gradpar_psi": np.zeros_like(fields["gradpar_psi"]),
        "delp2_one": np.zeros_like(fields["delp2_one"]),
        "bracket_self": np.zeros_like(fields["bracket_self"]),
    }
    for name, values in fields.items():
        error = values - expected[name]
        results[name] = {
            "finite": bool(np.isfinite(values).all()),
            "rms_error": float(np.sqrt(np.mean(error * error))),
            "maximum_absolute_error": float(np.max(np.abs(error))),
        }
    for path in case_dir.glob("BOUT.dmp.*.nc"):
        path.unlink()
    for path in case_dir.glob("BOUT.restart.*.nc"):
        path.unlink()
    for path in case_dir.glob("BOUT.log.*"):
        path.unlink()
    for path in case_dir.glob(".BOUT.pid.*"):
        path.unlink()
    settings = case_dir / "BOUT.settings"
    if settings.exists():
        settings.unlink()
    return results


def write_report(run_dir: Path, summary: dict[str, Any]) -> None:
    lines = [
        "# DIII-D BOUT++ Machine-Mesh Operator Validation",
        "",
        f"- Status: `{summary['status']}`",
        f"- Generated: `{summary['generated_at']}`",
        "- Model: custom static probe using BOUT++ derivative/operator implementations",
        "",
        "## Operator identities",
        "",
        "The probe evaluates these manufactured identities away from radial and",
        "poloidal guard/boundary cells:",
        "",
        "- `DDX(psixy) = 1`",
        "- `DDY(psixy) = 0`",
        "- `Grad_par(psixy) = 0`",
        "- `Delp2(1) = 0`",
        "- `bracket(psixy, psixy) = 0`",
        "",
        "| Operator | Coarse RMS error | Base RMS error | Fine RMS error | Improves coarse-to-fine |",
        "| --- | ---: | ---: | ---: | ---: |",
    ]
    for operator, trend in summary["trends"].items():
        lines.append(
            f"| `{operator}` | {trend['coarse_rms_error']:.6e} | "
            f"{trend['base_rms_error']:.6e} | {trend['fine_rms_error']:.6e} | "
            f"{trend['coarse_to_fine_improves']} |"
        )
    lines.extend(
        [
            "",
            f"- All physical-domain operator outputs finite: `{summary['all_outputs_finite']}`",
            f"- Identity checks within tolerances: `{summary['all_identity_checks_pass']}`",
            "",
            "## Topology boundary",
            "",
            "Exact lower-single-null topology requires a compatible multi-rank MPI",
            "decomposition that is blocked on the current host. As in the machine-mesh",
            "startup smoke, temporary serial-topology copies disable X-point connections",
            "and fill undefined `ShiftAngle` values with zero. Geometry and metric fields",
            "are otherwise unchanged.",
            "",
            "## Claim boundary",
            "",
            "This validates a focused set of BOUT++ operator identities on the DIII-D",
            "machine geometry. It is not a complete MMS suite, exact-X-point operator",
            "validation, physics-solution convergence result, or TCT validation.",
            "",
        ]
    )
    (run_dir / "diiid_bout_operator_validation_report.md").write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--executable", type=Path, default=DEFAULT_EXE)
    parser.add_argument("--python", type=Path, default=Path("/root/.venvs/hypnotoad/bin/python"))
    parser.add_argument("--run-dir", type=Path, default=DEFAULT_RUN_DIR)
    args = parser.parse_args()

    if not args.executable.exists():
        raise FileNotFoundError(f"Build the operator probe first: {args.executable}")
    if args.run_dir.exists():
        shutil.rmtree(args.run_dir)
    args.run_dir.mkdir(parents=True)

    with tempfile.TemporaryDirectory(prefix="diiid_operator_meshes_") as temp:
        mesh_dir = Path(temp)
        subprocess.run(
            [str(args.python), str(MESH_GENERATOR), "--run-dir", str(mesh_dir), "--keep-meshes"],
            check=True,
            capture_output=True,
            text=True,
        )
        cases = {}
        for name in MESH_NAMES:
            case_dir = args.run_dir / name
            case_dir.mkdir()
            serial_grid = case_dir / "serial_topology.grd.nc"
            write_serial_topology_grid(mesh_dir / f"{name}.grd.nc", serial_grid)
            write_input(case_dir, serial_grid)
            run_case(args.executable, case_dir)
            cases[name] = metrics(case_dir)
            serial_grid.unlink()

    trends = {}
    for operator in cases["base"]:
        values = [cases[name][operator]["rms_error"] for name in MESH_NAMES]
        trends[operator] = {
            "coarse_rms_error": values[0],
            "base_rms_error": values[1],
            "fine_rms_error": values[2],
            "coarse_to_fine_improves": values[2] < values[0],
        }

    tolerances = {
        "ddx_psi": 5e-3,
        "ddy_psi": 1e-10,
        "gradpar_psi": 1e-10,
        "delp2_one": 1e-8,
        "bracket_self": 1e-12,
    }
    all_finite = all(result["finite"] for case in cases.values() for result in case.values())
    identity_pass = all(
        cases[name][operator]["maximum_absolute_error"] <= tolerance
        for name in MESH_NAMES
        for operator, tolerance in tolerances.items()
    )
    passed = all_finite and identity_pass
    summary = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "status": (
            "DIIID_BOUT_OPERATOR_IDENTITIES_SUPPORTED_SERIAL_TOPOLOGY"
            if passed
            else "DIIID_BOUT_OPERATOR_IDENTITY_CHECK_FAILED"
        ),
        "tolerances": tolerances,
        "cases": cases,
        "trends": trends,
        "all_outputs_finite": all_finite,
        "all_identity_checks_pass": identity_pass,
    }
    (args.run_dir / "diiid_bout_operator_validation_summary.json").write_text(
        json.dumps(summary, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    write_report(args.run_dir, summary)
    print(json.dumps({"status": summary["status"], "all_identity_checks_pass": identity_pass}, indent=2))
    return 0 if passed else 1


if __name__ == "__main__":
    raise SystemExit(main())
