#!/usr/bin/env python3
"""Run serial-topology DIII-D elm-pb solution-convergence checks."""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import tempfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import netCDF4
import numpy as np

from diiid_bout_elm_mesh_smoke import write_serial_topology_grid


REPO = Path(__file__).resolve().parent
DEFAULT_EXE = Path("/tmp/bout-build/examples/elm-pb/elm_pb")
DEFAULT_RUN_DIR = REPO / "validation_runs" / "diiid_bout_elm_solution_convergence_default"
MESH_GENERATOR = REPO / "diiid_mesh_convergence_consistency.py"
FIELDS = ("U", "P", "Psi")
CASES = (
    ("coarse", "coarse", 8, 1e-4),
    ("base", "base", 8, 1e-4),
    ("fine", "fine", 8, 1e-4),
    ("base_dt_half", "base", 8, 5e-5),
    ("base_mz16", "base", 16, 1e-4),
)


def write_input(case_dir: Path, grid: Path, mz: int, dt: float) -> None:
    case_dir.mkdir(parents=True)
    (case_dir / "BOUT.inp").write_text(
        f"""# Generated by diiid_bout_elm_solution_convergence.py
MZ = {mz}
zperiod = 1
MXG = 2
MYG = 2
nout = {round(1e-3 / dt)}

[mesh]
file = "{grid.resolve()}"
staggergrids = false

[mesh:paralleltransform]
type = shifted

[solver]
type = rk4
output_step = {dt}
mxstep = 10000

[highbeta]
density = 1e19
evolve_jpar = false
evolve_pressure = true
include_jpar0 = false
include_curvature = true
compress = false
nonlinear = false
diamag = false
withflow = false
relax_j_vac = false
filter_z = true
filter_z_mode = 1
low_pass_z = 1
zonal_flow = false
zonal_field = false
zonal_bkgd = true
smooth_j_x = false
vacuum_pressure = 0.02
vacuum_trans = 0.01
vac_lund = 1e8
core_lund = 1e8
hyperresist = -1
viscos_par = -1
viscos_perp = 1e-4
hyperviscos = -1
diffusion_par = -1
diffusion_p4 = -1
diffusion_u4 = -1
diffusion_a4 = -1

[all]
scale = 0
bndry_all = dirichlet_o2

[U]
scale = 1e-8
function = gauss(x-0.5,0.1)*sin(z)

[P]
bndry_core = neumann

[Psi]
bndry_xin = zerolaplace
bndry_xout = zerolaplace

[Psi_loc]
bndry_xin = zerolaplace
bndry_xout = zerolaplace
""",
        encoding="utf-8",
    )


def run_case(executable: Path, case_dir: Path) -> None:
    env = dict(os.environ)
    env["UCX_TLS"] = env.get("BOUT_UCX_TLS", "self")
    result = subprocess.run(
        [str(executable), "-d", str(case_dir)], env=env, capture_output=True, text=True, check=False
    )
    if result.returncode:
        (case_dir / "bout_stdout.log").write_text(result.stdout, encoding="utf-8")
        (case_dir / "bout_stderr.log").write_text(result.stderr, encoding="utf-8")
        raise RuntimeError(f"elm-pb failed for {case_dir.name}")


def summarize(case_dir: Path, mesh_name: str, mz: int, dt: float) -> dict[str, Any]:
    with netCDF4.Dataset(case_dir / "BOUT.dmp.0.nc") as dataset:
        times = np.asarray(dataset["t_array"][:], dtype=float)
        fields = {}
        for name in FIELDS:
            values = np.asarray(dataset[name][:], dtype=float)[:, 2:-2, 2:-2, :]
            l2 = np.sqrt(np.mean(values * values, axis=(1, 2, 3)))
            maximum = np.max(np.abs(values), axis=(1, 2, 3))
            fields[name] = {
                "finite": bool(np.isfinite(values).all()),
                "l2_history": l2.tolist(),
                "max_abs_history": maximum.tolist(),
                "final_l2": float(l2[-1]),
                "final_max_abs": float(maximum[-1]),
            }
    for pattern in ("BOUT.dmp.*.nc", "BOUT.restart.*.nc", "BOUT.log.*", ".BOUT.pid.*"):
        for path in case_dir.glob(pattern):
            path.unlink()
    for name in ("BOUT.settings",):
        path = case_dir / name
        if path.exists():
            path.unlink()
    return {"mesh": mesh_name, "mz": mz, "dt": dt, "times": times.tolist(), "fields": fields}


def relative_difference(a: float, b: float) -> float:
    return abs(a - b) / max(abs(a), abs(b), 1e-300)


def write_report(run_dir: Path, summary: dict[str, Any]) -> None:
    lines = [
        "# DIII-D BOUT++ elm-pb Serial-Topology Solution Convergence",
        "",
        f"- Status: `{summary['status']}`",
        f"- Generated: `{summary['generated_at']}`",
        "",
        "| Case | Mesh | MZ | dt | Final U L2 | Final P L2 | Final Psi L2 |",
        "| --- | --- | ---: | ---: | ---: | ---: | ---: |",
    ]
    for name, case in summary["cases"].items():
        lines.append(
            f"| `{name}` | {case['mesh']} | {case['mz']} | {case['dt']:.1e} | "
            f"{case['fields']['U']['final_l2']:.6e} | {case['fields']['P']['final_l2']:.6e} | "
            f"{case['fields']['Psi']['final_l2']:.6e} |"
        )
    lines += [
        "",
        f"- All physical-domain histories finite: `{summary['all_finite']}`",
        f"- Base timestep-halving maximum scalar difference: `{summary['timestep_max_relative_difference']:.6e}`",
        f"- Base MZ 8-to-16 maximum scalar difference: `{summary['toroidal_max_relative_difference']:.6e}`",
        "",
        "The proportional mesh cases quantify solution sensitivity but are not required",
        "to agree tightly because each Hypnotoad mesh changes the discrete machine",
        "geometry and metric representation. The timestep and toroidal checks isolate",
        "numerical sensitivities on the same base mesh.",
        "",
        "## Claim boundary",
        "",
        "This is short-duration linear evolution convergence with the serial topology",
        "override and without Jpar0. It is not exact-X-point evolution, validated ELM",
        "growth, nonlinear saturation, TCT control validation, or experimental agreement.",
        "",
    ]
    (run_dir / "diiid_bout_elm_solution_convergence_report.md").write_text(
        "\n".join(lines), encoding="utf-8"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--executable", type=Path, default=DEFAULT_EXE)
    parser.add_argument("--python", type=Path, default=Path("/root/.venvs/hypnotoad/bin/python"))
    parser.add_argument("--run-dir", type=Path, default=DEFAULT_RUN_DIR)
    args = parser.parse_args()
    if args.run_dir.exists():
        shutil.rmtree(args.run_dir)
    args.run_dir.mkdir(parents=True)

    with tempfile.TemporaryDirectory(prefix="diiid_elm_convergence_") as temp:
        mesh_dir = Path(temp)
        subprocess.run(
            [str(args.python), str(MESH_GENERATOR), "--run-dir", str(mesh_dir), "--keep-meshes"],
            check=True,
            capture_output=True,
            text=True,
        )
        serial_grids = {}
        for mesh_name in ("coarse", "base", "fine"):
            grid = mesh_dir / f"{mesh_name}_serial.grd.nc"
            write_serial_topology_grid(mesh_dir / f"{mesh_name}.grd.nc", grid)
            serial_grids[mesh_name] = grid
        cases = {}
        for case_name, mesh_name, mz, dt in CASES:
            case_dir = args.run_dir / case_name
            write_input(case_dir, serial_grids[mesh_name], mz, dt)
            run_case(args.executable, case_dir)
            cases[case_name] = summarize(case_dir, mesh_name, mz, dt)

    def comparison(first: str, second: str) -> dict[str, float]:
        return {
            field: relative_difference(
                cases[first]["fields"][field]["final_l2"], cases[second]["fields"][field]["final_l2"]
            )
            for field in FIELDS
        }

    timestep = comparison("base", "base_dt_half")
    toroidal = comparison("base", "base_mz16")
    all_finite = all(field["finite"] for case in cases.values() for field in case["fields"].values())
    timestep_max = max(timestep.values())
    toroidal_max = max(toroidal.values())
    passed = all_finite and timestep_max < 5e-3 and toroidal_max < 5e-3
    summary = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "status": "DIIID_ELM_PB_SERIAL_SOLUTION_CONVERGENCE_SUPPORTED" if passed else "DIIID_ELM_PB_SERIAL_SOLUTION_CONVERGENCE_FAILED",
        "cases": cases,
        "timestep_relative_differences": timestep,
        "toroidal_relative_differences": toroidal,
        "timestep_max_relative_difference": timestep_max,
        "toroidal_max_relative_difference": toroidal_max,
        "all_finite": all_finite,
    }
    (args.run_dir / "diiid_bout_elm_solution_convergence_summary.json").write_text(
        json.dumps(summary, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    write_report(args.run_dir, summary)
    print(json.dumps({"status": summary["status"], "timestep_max": timestep_max, "toroidal_max": toroidal_max}, indent=2))
    return 0 if passed else 1


if __name__ == "__main__":
    raise SystemExit(main())
