#!/usr/bin/env python3
"""Run the official BOUT++ elm-pb model on DIII-D Hypnotoad geometry."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import netCDF4
import numpy as np


REPO = Path(__file__).resolve().parent
DEFAULT_GRID = (
    REPO
    / "validation_inputs"
    / "geqdsk_efit_baseline"
    / "diii_d_158103_03796"
    / "diii_d_158103_03796_hypnotoad.grd.nc"
)
DEFAULT_EXE = Path("/tmp/bout-build/examples/elm-pb/elm_pb")
DEFAULT_RUN_DIR = REPO / "validation_runs" / "diiid_bout_elm_mesh_smoke_default"
TOROIDAL_RESOLUTIONS = (8, 16)
OUTPUT_FIELDS = ("U", "P", "Psi")


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def write_serial_topology_grid(source: Path, output: Path) -> dict[str, int]:
    output.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, output)
    with netCDF4.Dataset(output, "r+") as dataset:
        nx = len(dataset.dimensions["x"])
        ny = len(dataset.dimensions["y"])
        topology = {
            "ixseps1": nx,
            "ixseps2": nx,
            "jyseps1_1": -1,
            "jyseps1_2": ny // 2,
            "jyseps2_1": ny // 2,
            "jyseps2_2": ny - 1,
            "ny_inner": ny // 2,
        }
        for name, value in topology.items():
            dataset.variables[name].assignValue(value)
        shift_angle = np.asarray(dataset.variables["ShiftAngle"][:])
        shift_angle[~np.isfinite(shift_angle)] = 0.0
        dataset.variables["ShiftAngle"][:] = shift_angle
        dataset.setncattr(
            "validation_topology_override",
            "Serial smoke only: X-point connections disabled and undefined ShiftAngle values set to zero; geometry, magnetic, pressure, curvature, Jacobian, and metric fields unchanged.",
        )
    return topology


def write_input(case_dir: Path, grid: Path, mz: int) -> None:
    case_dir.mkdir(parents=True, exist_ok=True)
    text = f"""# Generated by diiid_bout_elm_mesh_smoke.py
# Official BOUT++ elm-pb reduced-MHD machine-geometry smoke.
MZ = {mz}
zperiod = 1
MXG = 2
MYG = 2
nout = 2

[mesh]
file = "{grid.resolve()}"
staggergrids = false

[mesh:paralleltransform]
type = shifted

[solver]
type = rk4
output_step = 1e-4
mxstep = 10000

[highbeta]
density = 1e19
evolve_jpar = false
evolve_pressure = true
include_jpar0 = false
include_curvature = true
compress = false
nonlinear = false
diamag = false
withflow = false
relax_j_vac = false
filter_z = true
filter_z_mode = 1
low_pass_z = 1
zonal_flow = false
zonal_field = false
zonal_bkgd = true
smooth_j_x = false
vacuum_pressure = 0.02
vacuum_trans = 0.01
vac_lund = 1e8
core_lund = 1e8
hyperresist = -1
viscos_par = -1
viscos_perp = 1e-4
hyperviscos = -1
diffusion_par = -1
diffusion_p4 = -1
diffusion_u4 = -1
diffusion_a4 = -1

[all]
scale = 0
bndry_all = dirichlet_o2

[U]
scale = 1e-8
function = gauss(x-0.5,0.1)*sin(z)

[P]
bndry_core = neumann

[Psi]
bndry_xin = zerolaplace
bndry_xout = zerolaplace

[Psi_loc]
bndry_xin = zerolaplace
bndry_xout = zerolaplace
"""
    (case_dir / "BOUT.inp").write_text(text, encoding="utf-8")


def run_case(executable: Path, case_dir: Path) -> None:
    environment = dict(os.environ)
    environment["UCX_TLS"] = environment.get("BOUT_UCX_TLS", "self")
    result = subprocess.run(
        [str(executable), "-d", str(case_dir)],
        env=environment,
        capture_output=True,
        text=True,
        check=False,
    )
    (case_dir / "bout_stdout.log").write_text(result.stdout, encoding="utf-8")
    (case_dir / "bout_stderr.log").write_text(result.stderr, encoding="utf-8")
    if result.returncode:
        raise RuntimeError(f"BOUT++ failed for {case_dir.name}; see bout_stdout.log")


def summarize_case(case_dir: Path, mz: int) -> dict[str, Any]:
    output = case_dir / "BOUT.dmp.0.nc"
    if not output.exists():
        raise FileNotFoundError(output)
    result: dict[str, Any] = {"case": case_dir.name, "mz": mz, "fields": {}}
    with netCDF4.Dataset(output) as dataset:
        times = np.asarray(dataset.variables["t_array"][:], dtype=float)
        result["times"] = times.tolist()
        for name in OUTPUT_FIELDS:
            values = np.asarray(dataset.variables[name][:], dtype=float)
            physical = values[:, 2:-2, 2:-2, :]
            finite = np.isfinite(physical)
            result["fields"][name] = {
                "shape": list(values.shape),
                "physical_shape": list(physical.shape),
                "physical_domain_finite": bool(finite.all()),
                "guard_cells_contain_nonfinite": bool(
                    not np.isfinite(values[:, :2, :, :]).all()
                    or not np.isfinite(values[:, -2:, :, :]).all()
                    or not np.isfinite(values[:, :, :2, :]).all()
                    or not np.isfinite(values[:, :, -2:, :]).all()
                ),
                "initial_max_abs": float(np.max(np.abs(physical[0]))),
                "final_max_abs": float(np.max(np.abs(physical[-1]))),
                "final_l2": float(np.sqrt(np.mean(physical[-1] ** 2))),
            }
    result["all_physical_fields_finite"] = all(
        field["physical_domain_finite"] for field in result["fields"].values()
    )
    for path in case_dir.glob("BOUT.dmp.*.nc"):
        path.unlink()
    for path in case_dir.glob("BOUT.restart.*.nc"):
        path.unlink()
    settings = case_dir / "BOUT.settings"
    if settings.exists():
        settings.unlink()
    for path in case_dir.glob(".BOUT.pid.*"):
        path.unlink()
    for path in case_dir.glob("BOUT.log.*"):
        path.unlink()
    for name in ("bout_stdout.log", "bout_stderr.log"):
        path = case_dir / name
        if path.exists():
            path.unlink()
    return result


def write_report(run_dir: Path, summary: dict[str, Any]) -> None:
    lines = [
        "# DIII-D BOUT++ elm-pb Machine-Mesh Smoke",
        "",
        f"- Status: `{summary['status']}`",
        f"- Generated: `{summary['generated_at']}`",
        f"- BOUT++ revision: `{summary['bout_revision']}`",
        f"- Source mesh SHA-256: `{summary['source_grid_sha256']}`",
        "- Model: official BOUT++ `elm-pb` high-beta reduced MHD",
        "",
        "## Results",
        "",
        "| MZ | Final time | U finite | P finite | Psi finite | Final max abs U |",
        "| ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    for case in summary["cases"]:
        fields = case["fields"]
        lines.append(
            f"| {case['mz']} | {case['times'][-1]:.6g} | {fields['U']['physical_domain_finite']} | "
            f"{fields['P']['physical_domain_finite']} | {fields['Psi']['physical_domain_finite']} | "
            f"{fields['U']['final_max_abs']:.8e} |"
        )
    convergence = summary["toroidal_resolution_check"]
    lines.extend(
        [
            "",
            "Both toroidal resolutions loaded the DIII-D geometry, pressure, curvature,",
            "magnetic, Jacobian, and shifted-metric fields and completed reduced-MHD time",
            "evolution with finite evolved fields in the physical domain.",
            "",
            f"- Final max-abs U relative difference: `{convergence['U']['relative_difference']:.8e}`",
            f"- Final max-abs P relative difference: `{convergence['P']['relative_difference']:.8e}`",
            f"- Final max-abs Psi relative difference: `{convergence['Psi']['relative_difference']:.8e}`",
            "",
            "## Topology and physics boundary",
            "",
            "The exact lower-single-null mesh loads successfully, but BOUT++ requires a",
            "14-rank Y decomposition for its 24/32-cell divertor/core regions. This host",
            "cannot launch multi-rank MPI because network-interface access is denied.",
            "For the completed serial smoke cases, the runner creates a temporary grid",
            "copy that disables X-point connections while leaving geometry, magnetic,",
            "pressure, curvature, Jacobian, and metric fields unchanged. Undefined",
            "`ShiftAngle` values outside their original applicable region are set to zero",
            "for the temporary serial topology.",
            "",
            "The equilibrium grid does not contain `Jpar0`, so equilibrium-current drive",
            "is disabled. The cases are linear, short-duration startup tests with a small",
            "vorticity perturbation. This validates BOUT++ machine-mesh ingestion and",
            "finite reduced-MHD evolution only; it does not validate ELM growth, TCT",
            "control, exact divertor topology evolution, or experimental diagnostics.",
            "",
            "## Next step",
            "",
            "Run the unchanged exact-topology grid with 14 MPI ranks on a conventional",
            "Linux/HPC host, add a defensible `Jpar0` equilibrium-current profile, then",
            "perform linear growth-rate and controlled/uncontrolled comparisons.",
            "",
        ]
    )
    (run_dir / "diiid_bout_elm_mesh_smoke_report.md").write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--grid", type=Path, default=DEFAULT_GRID)
    parser.add_argument("--executable", type=Path, default=DEFAULT_EXE)
    parser.add_argument("--run-dir", type=Path, default=DEFAULT_RUN_DIR)
    args = parser.parse_args()

    if not args.executable.exists():
        raise FileNotFoundError(f"elm-pb executable not found: {args.executable}")
    if args.run_dir.exists():
        shutil.rmtree(args.run_dir)
    args.run_dir.mkdir(parents=True)

    serial_grid = args.run_dir / "diiid_serial_topology.grd.nc"
    serial_topology = write_serial_topology_grid(args.grid, serial_grid)
    cases = []
    for mz in TOROIDAL_RESOLUTIONS:
        case_dir = args.run_dir / f"mz{mz}"
        write_input(case_dir, serial_grid, mz)
        run_case(args.executable, case_dir)
        cases.append(summarize_case(case_dir, mz))

    serial_grid.unlink()
    convergence = {}
    for name in OUTPUT_FIELDS:
        low = cases[0]["fields"][name]["final_max_abs"]
        high = cases[1]["fields"][name]["final_max_abs"]
        convergence[name] = {
            "mz8_final_max_abs": low,
            "mz16_final_max_abs": high,
            "relative_difference": abs(high - low) / max(abs(high), abs(low), 1e-300),
        }
    passed = (
        all(case["all_physical_fields_finite"] and len(case["times"]) == 3 for case in cases)
        and convergence["U"]["relative_difference"] < 1e-6
        and convergence["P"]["relative_difference"] < 0.1
        and convergence["Psi"]["relative_difference"] < 0.1
    )
    summary = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "status": (
            "DIIID_BOUT_ELM_PB_SERIAL_TOPOLOGY_SMOKE_PASS_EXACT_TOPOLOGY_MPI_BLOCKED"
            if passed
            else "DIIID_BOUT_ELM_PB_SMOKE_FAILED"
        ),
        "bout_revision": "3e317cbc18b4ad3839cfff67aded3bff4b5fb9f9",
        "source_grid": str(args.grid.relative_to(REPO)),
        "source_grid_sha256": sha256(args.grid),
        "source_topology": {
            "nx": 40,
            "ny": 112,
            "ixseps1": 24,
            "ixseps2": 40,
            "jyseps1_1": 23,
            "jyseps1_2": 56,
            "jyseps2_1": 56,
            "jyseps2_2": 87,
        },
        "required_exact_topology_mpi_ranks": 14,
        "serial_topology_override": serial_topology,
        "toroidal_resolution_check": convergence,
        "cases": cases,
    }
    (args.run_dir / "diiid_bout_elm_mesh_smoke_summary.json").write_text(
        json.dumps(summary, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    write_report(args.run_dir, summary)
    print(json.dumps({"status": summary["status"], "cases": len(cases)}, indent=2))
    return 0 if passed else 1


if __name__ == "__main__":
    raise SystemExit(main())
